-- CIDs faltantes identificados na auditoria SESMT (2026-08-21)
INSERT INTO cid_referencia (codigo, descricao) VALUES
('A49.9', 'Infecção bacteriana não especificada'),
('F41.2', 'Transtorno misto ansioso e depressivo'),
('F41.8', 'Outros transtornos ansiosos especificados'),
('F41.9', 'Transtorno ansioso não especificado'),
('G43.0', 'Enxaqueca sem aura [enxaqueca comum]'),
('G43.9', 'Enxaqueca, sem especificação'),
('H10.3', 'Conjuntivite aguda não especificada'),
('H10.9', 'Conjuntivite não especificada'),
('H65.9', 'Otite média não-supurativa, não especificada'),
('I21.9', 'Infarto agudo do miocárdio não especificado'),
('J01.9', 'Sinusite aguda não especificada'),
('J02.9', 'Faringite aguda não especificada'),
('J03.9', 'Amigdalite aguda não especificada'),
('J11.1', 'Influenza [gripe] com outras manifestações respiratórias, devida a vírus não identificado'),
('J11.8', 'Influenza [gripe] com outras manifestações, devida a vírus não identificado'),
('K01.1', 'Dentes impactados'),
('K05.3', 'Periodontite crônica'),
('L23.3', 'Dermatite alérgica de contato devido a drogas em contato com a pele'),
('M75.1', 'Síndrome do manguito rotador'),
('M75.5', 'Bursite do ombro'),
('M77.3', 'Esporão do calcâneo'),
('M79.9', 'Transtorno dos tecidos moles não especificado'),
('N10',   'Nefrite túbulo-intersticial aguda'),
('N39.9', 'Transtornos não especificados do aparelho urinário'),
('O10.9', 'Hipertensão pré-existente não especificada, complicando a gravidez, o parto e o puerpério'),
('O26.9', 'Afecções ligadas a gravidez, não especificadas'),
('R10.0', 'Abdome agudo'),
('R10.2', 'Dor pélvica e perineal'),
('R10.4', 'Outras dores abdominais e as não especificadas'),
('S52.5', 'Fratura da extremidade distal do rádio'),
('S90.9', 'Traumatismo superficial do tornozelo e do pé, não especificado'),
('S92.9', 'Fratura do pé não especificada'),
('S93.6', 'Entorse e distensão de outras partes e de partes não especificadas do pé'),
('T30.2', 'Queimadura de segundo grau, parte do corpo não especificada'),
('W54.9', 'Mordedura ou golpe provocado por cão - local não especificado'),
('Y28.9', 'Contato com objeto cortante ou penetrante, intenção não determinada - local não especificado'),
('Z00.0', 'Exame médico geral'),
('Z30.5', 'Supervisão de dispositivo anticoncepcional (intra-uterino)'),
('Z34.9', 'Supervisão de gravidez normal, não especificada'),
('Z54.0', 'Convalescença após cirurgia'),
('Z54.9', 'Convalescença após tratamento não especificado')
ON CONFLICT (codigo) DO NOTHING;
